$schema: https://api.gitbook.com/gitbook-docs.yaml
site:
  title: MM - Store
  structure:
    - type: space
      key: mm-store-docs
      title: Documentation
      path: docs
      default: true
      content:
        directory: ./
        language: en
